### ISSUE TITLE
Rtl support

### ISSUE THREAD

**Issue by sahnounekhaled** [Ismanyan/Pdf_flipbook.demo.github.io#2]
Hi
your flipbook for pdf file work finebut
i want to flip my pdf file from right to left direction
can you help me to make changes in  your javascript files ???
thank you

**Comment by NSR-WORLD** [comment]
Find rightToLeft: !1 (around line 31 in flipbook.js)  and change it to rightToLeft: !0

**Comment by dwicahyo1512** [comment]
can I adjust the display of the flipbook and change it?
